name: flutter_dev_panel
description: "A comprehensive Flutter debug panel for development with network monitoring, performance tracking, and environment switching."
version: 0.0.1
homepage: https://github.com/royorange/flutter-dev-panel

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # 核心依赖
  logger: ^2.6.0
  
  # 网络监控
  dio: ^5.4.0
  intl: ^0.19.0  # 时间格式化
  
  # 设备信息
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  
  # 性能监控
  # flutter_fps: ^2.0.0  # 暂时注释，后续寻找替代方案
  
  # 存储
  shared_preferences: ^2.2.3
  
  # UI 组件
  flutter_slidable: ^3.1.0
  shimmer: ^3.0.0
  
  # 传感器（摇一摇）
  sensors_plus: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
