name: flutter_dev_panel_network
description: Network monitoring module for Flutter Dev Panel
version: 0.0.1
homepage: https://github.com/royorange/flutter-dev-panel

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dev_panel_core:
    path: ../flutter_dev_panel_core
  dio: ^5.4.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
